-- Renaming columns
ALTER TABLE default_table_staging
  CHANGE MyUnknownColumn ID INT,
  CHANGE X1 Given_credit INT,
  CHANGE X2 Gender VARCHAR(10),
  CHANGE X3 Education VARCHAR(20),
  CHANGE X4 Marital_status VARCHAR(20),
  CHANGE X5 Age INT,
  CHANGE X6 Sept_delay VARCHAR(50),
  CHANGE X7 August_delay VARCHAR(50),
  CHANGE X8 July_delay VARCHAR(50),
  CHANGE X9 June_delay VARCHAR(50),
  CHANGE X10 May_delay VARCHAR(50),
  CHANGE X11 April_delay VARCHAR(50),
  CHANGE X12 Sept_bill INT,
  CHANGE X13 August_bill INT,
  CHANGE X14 July_bill INT,
  CHANGE X15 June_bill INT,
  CHANGE X16 May_bill INT,
  CHANGE X17 April_bill INT,
  CHANGE X18 Sept_payment INT,
  CHANGE X19 August_payment INT,
  CHANGE X20 July_payment INT,
  CHANGE X21 June_payment INT,
  CHANGE X22 May_payment INT,
  CHANGE X23 April_payment INT,
  CHANGE Y Oct_default VARCHAR(20);